src/MMIBundle/Form/Type/UserAddJobType.php
<?php

namespace MMIBundle\Form\Type;

use MMIBundle\Model\Company;
use MMIBundle\Model\CompanyQuery;
use MMIBundle\Model\Profession;
use MMIBundle\Model\ProfessionQuery;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserAddJobType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $years = [];
        for ($year = date('Y', time()); $year >= 1990; $year--) $years[$year] = $year;

        $builder
            ->add('job_id', 'hidden', ['mapped' => false])
            ->add('profession_id', 'text', [])
            ->add('company_id', 'text', [])
            ->add('yearFrom', 'choice', ['choices' => $years])
            ->add('yearTo', 'choice', ['choices' => $years])
            ->add('description', 'textarea', []);

        $builder->get("profession_id")->addModelTransformer(new CallbackTransformer(
            function ($original) {
                $profession = "";
                if ($original != null) $profession = $original->getName();
                return $profession;
            },
            function ($submitted) {
                $profession = ProfessionQuery::create()->filterByName($submitted)->findOne();
                if ($profession == null) {
                    $profession = new Profession();
                    $profession->setName($submitted)->save();
                }
                return $profession->getId();
            }
        ));

        $builder->get("company_id")->addModelTransformer(new CallbackTransformer(
            function ($original) {
                $company = "";
                if ($original != null) $company = $original->getName();
                return $company;
            },
            function ($submitted) {
                $company = CompanyQuery::create()->filterByName($submitted)->findOne();
                if ($company == null) {
                    $company = new Company();
                    $company->setName($submitted)->save();
                }
                return $company->getId();
            }
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array("data_class" => 'MMIBundle\Model\UserJob'));
    }

    public function getName()
    {
        return "UserAddJobType";
    }
}

src/MMIBundle/Controller/StageController.php
<?php

namespace MMIBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use MMIBundle\Model\InternshipQuery;
use MMIBundle\Model\Internship;
use MMIBundle\Model\ConfigQuery;
use MMIBundle\Form\Type\BeforeInternshipType;
use MMIBundle\Form\Type\StagesEtablisType;



class StageController extends BaseController
{
    public function myInternshipAction(Request $request)
    {
        // On récupère date de début et de fin de stage de l'année courante
        // dans la table de configuration de l'admin

        $config = ConfigQuery::create()
            ->findOneById(1);

        $begining = $config->getInternshipBegining();
        $ending = $config->getInternshipEnding();

        // on indique si on est avant, pendant ou après le stage
        // en fonction du datetime courant

        $current_datetime = new \DateTime(date('Y-m-d h:i:s a', time()));

        $state = null;

        if($current_datetime < $begining){
            $state = 'before';
        }elseif(($begining < $current_datetime) && ($current_datetime < $ending)){
            $state = 'during';
        }elseif($ending < $current_datetime){
            $state = 'after';
        }

        // si on est avant le date de début
        // on affiche la section 'avant'

        // On vérifie si l'utilisateur est connecté (externalisé)
        $response = $this->checkAccess();
        if ($response != null) return $this->redirectToRoute($response);

        // L'utilisateur est connecté, on stocke ses infos en session
        $connectedUser = $this->get('session')->get('Account');
        // On stocke son id dans une variable pour y accéder plus rapidement
        $connectedUserId = $connectedUser->getId();

        if($state == 'before'){

            $this->params['etape'] = 'avant';

            // On essaye de récupérer son stage
            $stage = InternshipQuery::create()->findOneByUserId($connectedUserId);

            $result = null;

            // Si aucun stage n'a jamais été créé on crée un nouvel objet stage
            if($stage == null){
                $stage = new Internship;
            }elseif($stage->getValide() == 1){

                // Si le stage a été validé on affiche un message de confirmation à la place du formulaire
                $result = 'Mme Gil a validé ton stage, Élodie éditera prochainement ta convention.';

                if($stage->getEtabli() == 1){

                    // Si la convention a été établie on affiche un message de confirmation à la place du formulaire
                    $result = 'Élodie a édité ta convention, elle t\'attend au secrétariat !';

                }

                $this->params['result'] = $result;
                return $this->render("MMIBundle:Stage:my_internship.html.twig", $this->params);

            }elseif($stage->getValide() == 2){

                // Si le stage a été refusé on affiche un message d'alerte
                $result = 'Mme Gil a refusé ton stage, nous t\' invitons à aller la voir.';
                $this->params['result'] = $result;
                return $this->render("MMIBundle:Stage:my_internship.html.twig", $this->params);
            }else{

                // Autrement on affiche un message de confirmation à la place du formulaire
                $result = 'Mme Gil a bien reçu ta demande, elle la validera bientôt.';
                $this->params['result'] = $result;
                return $this->render("MMIBundle:Stage:my_internship.html.twig", $this->params);
            }

            // On crée le formulaire de l'étape "before"
            // On l'associe au modèle de formulaire correspondant
            // Et on l'associe à l'objet stage créé précédement

            $beforeForm = $this->createForm(new beforeInternshipType(), $stage);


            // On essaye de récupérer les données du éventuelle requête POST

            $beforeForm->handleRequest($request);

            // Si un formulaire a été soumis et qu'il est valide

            if ($beforeForm->isSubmitted() && $beforeForm->isValid()) {

                // Si c'est le formulaire "before"

                if($beforeForm->getName() == 'beforeInternship'){

                    // On affecte manuellement l'id utilisateur

                    $stage->setUserId($connectedUserId);

                    // On affecte manuellement les dates de début et fin de stage de la table config

                    $stage->setInternshipBegining($begining);
                    $stage->setInternshipEnding($ending);

                    // On sauvegarde l'objet stage dans la BDD

                    $stage->save();

                    // On envoie un message de configuration à la vue

                    $result = 'Mme Gil a bien reçu ta demande, elle la validera bientôt.';
                    $this->params['result'] = $result;

                    // On appelle la vue avec un message de confirmation
                    return $this->render("MMIBundle:Stage:my_internship.html.twig", $this->params);
                }

            }

            // On affiche le formulaire
            $this->params['beforeForm'] = $beforeForm->createView();
            $this->params['result'] = $result;
            return $this->render("MMIBundle:Stage:my_internship.html.twig", $this->params);


        }elseif($state == 'during'){

            // si on est entre la date de début et de fin
            // on affiche la section 'pendant'

            $internship = InternshipQuery::create()
                ->filterByUserId($connectedUserId)
                ->findOne();

            $dateB = $internship->getInternshipBegining();
            $dateE = $internship->getInternshipEnding();

            $dateC = new \DateTime(date('Y-m-d h:i:s a', time()));

            $interval = $dateB->diff($dateE);
            $days = $interval->days;
            $nb_weeks = ($days+3)/7;
            echo 'Nombre de semaines :'.$nb_weeks;

            $c_interval = $dateB->diff($dateC);
            $days = $c_interval->days;
            $curr_week = ceil(($days)/7);
            echo 'Semaine atuelle :'.$curr_week;

            $this->params['etape'] = 'pendant';
            return $this->render("MMIBundle:Stage:my_internship.html.twig", $this->params);

        }elseif($state == 'after'){

            // si on est après la date de fin
            // on affiche la section après

            $this->params['etape'] = 'apres';
            return $this->render("MMIBundle:Stage:my_internship.html.twig", $this->params);

        }

    }

    public function stagesPromoAction(){

        $internships = InternshipQuery::create()
            ->filterByValide(null)
            ->find();

        // On vérifie si l'utilisateur est connecté (externalisé)
        $response = $this->checkAccess();
        if ($response != null) return $this->redirectToRoute($response);

        $this->params['internships'] = $internships;
        return $this->render("MMIBundle:Stage:stages_promo.html.twig", $this->params);
    }

    public function internshipValidationAction($id, $valide){

        $internship = InternshipQuery::create()
            ->findOneById($id);
        $internship->setValide($valide);
        $internship->save();

        return $this->redirectToRoute('mmi_stages_promo');
    }

    public function stagesValidesAction(){

        $internships = InternshipQuery::create()
            ->filterByValide(true)
            ->filterByEtabli(null)
            ->find();

        // On vérifie si l'utilisateur est connecté (externalisé)
        $response = $this->checkAccess();
        if ($response != null) return $this->redirectToRoute($response);

        $this->params['internships'] = $internships;
        return $this->render("MMIBundle:Stage:stages_valides.html.twig", $this->params);
    }

    public function agreementValidationAction($id){

        $internship = InternshipQuery::create()
            ->findOneById($id);
        $internship->setEtabli(true);
        $internship->save();

        return $this->redirectToRoute('mmi_stages_valides');
    }

    public function stagesEtablisAction(Request $request){

        // On vérifie si l'utilisateur est connecté (externalisé)
        $response = $this->checkAccess();
        if ($response != null) return $this->redirectToRoute($response);

        $internships = InternshipQuery::create()
            ->filterByEtabli(true)
            ->find();

        $stagesEtablisForms = [];

        foreach($internships as $internship) {
            $stagesEtablisForm = $this->createForm(new StagesEtablisType(), $internship);
            $stagesEtablisForms[$internship->getId()] = $stagesEtablisForm;
        }

        if ($request->isMethod('POST')) {
            if ($request->request->has('stageEtablis')) {
                $data = $request->request->get('stageEtablis');

                if (isset($data['id'])) {
                    $id = $data['id'];

                    if (isset($stagesEtablisForms[$id])) {
                        $form = $stagesEtablisForms[$id];

                        $form->handleRequest($request);

                        if ($form->isValid()) {
                            $form->getData()->save();
                        }
                    }
                }
            }
        }

        // Si un formulaire a été soumis et qu'il est valide

        /*
        if ($stagesEtablisForm->isSubmitted() && $stagesEtablisForm->isValid()) {

            // Si c'est le formulaire "before"

            if($beforeForm->getName() == 'beforeInternship'){

                // On affecte manuellement l'id utilisateur

                $stage->setUserId($connectedUserId);

                // On affecte manuellement les dates de début et fin de stage de la table config

                $stage->setInternshipBegining($begining);

src/MMIBundle/Resources/views/Stage/my_internship.html.twig
{% extends "MMIBundle::template.html.twig" %}

{% block title %}Gérer mon stage{% endblock %}

{% block includeHead %}
    <link rel="stylesheet" href="{{ asset("assets/jquery-ui-1.11.4/jquery-ui.min.css") }}">
    {#<script type="text/javascript" src="{{ asset("assets/jquery-latest.min.js") }}"></script>#}
    <script type="text/javascript" src="{{ asset('js/form_regex.js') }}"></script>
{% endblock %}

{% block bodyClass %}internship{% endblock %}

{% block header %}
    class="before"
{% endblock %}

{% block headerExtended %}
        <div class="content">
            <a href="{{ path("mmi_homepage") }}" class="logo white transition">331 Acceuil</a>
            <h1>Gérer mon stage</h1>
            <p>Tu as trouvé ton stage ? Cette section te permet de soumettre ta proposition à la validation de Madame Gil. En cas de problème, n'hésite pas à <a href="mailto:pascale.gil@gmail.com">la contacter</a></p>
            <p>Ca y est, tu as commencé ton stage ! Nous t'invitons à revenir dans cet espace chaque semaine pour compléter
                ton journal de stage. Il pourra être lu par ton tuteur ou tout autre membre de la communauté intéressé par
                ton stage.</p>
            <p>Maintenant que ton stage est terminé, nous t'invitons à remplir ce dernier formulaire. Une fiche stage sera
                crée et associée à ton profil. Elle permettra à tous les membres de la communauté d'en savoir plus sur ton
                stage.</p>
            <!--
            <div>
                <h2>Niveau de formation</h2>
                <div>
                    <button class="white big">DUT</button>
                    <button class="white big">Licence</button>
                </div>
            </div>
            -->
        </div>
{% endblock %}

{% block content %}
    <main>

        <section class="etapes">
            <div>
                <div {% if etape == 'avant' %}class="current"{% endif %}>
                    <div>1</div>
                    <div id="before">Avant le stage</div>
                </div>
                <div {% if etape == 'pendant' %}class="current"{% else %}class="disabled"{% endif %}>
                    <div>2</div>
                    <div id="during">Pendant le stage</div>
                </div>
                <div {% if etape == 'apres' %}class="current"{% else %}class="disabled"{% endif %}>
                    <div>3</div>
                    <div id="after">Après le stage</div>
                </div>
            </div>
        </section>
        <section class="before formulaire current {% if etape != 'avant' %}hidden{% endif %}">
            {%  if beforeForm is defined %}
                {{ form_start(beforeForm) }}
                    <h1>Avant le stage</h1>
                    <!--
                    <h2>Date du stage</h2>
                    <div class="dateSelector">
                        {#{{ form_widget(beforeForm.dateBegining,
                        {"attr": {
                            "class": "big stretch"},
                            "id": "datePicker"}) }}#}
                    </div>
                    <div class="dateSelector">
                        {#{{ form_widget(beforeForm.dateEnding,
                        {"attr": {
                            "class": "big stretch"},
                            "id": "datePicker"}) }}#}
                    </div>
                    -->
                    <h2>Place dans l'entreprise</h2>

                    <div class="ui-widget">
                        {{ form_widget(beforeForm.companyId, {'attr': {'class': 'big', 'placeholder': 'Nom de l\'entreprise'}}) }}
                    </div>

                    {{ form_widget(beforeForm.workFunction, {'attr': {'class': 'big', 'placeholder': 'Service d\'affectation'}}) }}
                    <!--<h2>Avez-vous répondu à une offre ?</h2>
                    <p><input type="radio" value="oui" id="oui"><label for="oui">Oui</label></p>
                    <p><input type="radio" value="non" id="non"><label for="non">Non</label></p>
                    <p>Saisissez le numéro de l'offre :
                        {# {{ form_widget(beforeForm.offerId, {'attr': {'class': 'big', 'style': 'margin-top:15px'}}) }}#}
                    </p>-->
                    <h2>Signataire de la convention</h2>
                    {{ form_widget(beforeForm.signatoryFirstname, {'attr': {'class': 'big', 'placeholder': 'Prénom'}}) }}
                    {{ form_widget(beforeForm.signatoryLastname, {'attr': {'class': 'big', 'placeholder': 'Nom'}}) }}
                    {{ form_widget(beforeForm.signatoryFunction, {'attr': {'class': 'big', 'placeholder': 'Fonction'}}) }}
                    <h2>Maître de stage</h2>
                    {{ form_widget(beforeForm.masterFirstname, {'attr': {'class': 'big', 'placeholder': 'Prénom'}}) }}
                    {{ form_widget(beforeForm.masterLastname, {'attr': {'class': 'big', 'placeholder': 'Nom'}}) }}
                    {{ form_widget(beforeForm.masterEmail, {'attr': {'class': 'big', 'placeholder': 'Email'}}) }}
                    {{ form_widget(beforeForm.masterTelephone, {'attr': {'class': 'big', 'placeholder': 'Téléphone'}}) }}
                    <h2>Ton job</h2>
                    {{ form_widget(beforeForm.description, {'attr': {'class': 'big', 'placeholder': 'Missions qui te sont confiées', 'cols': '30', 'rows': '20'}}) }}
                    {{ form_widget(beforeForm.valider, {'attr': {'class': 'big', 'style': 'margin-top: 30px;display: block', 'value': 'Valider'}} ) }}
                {{ form_end(beforeForm) }}
            {% else %}
            <h1 class="waiting">{% if result is defined %}{{ result }}{% endif %}</h1>
            {%  endif %}
        </section>
        <section class="during formulaire current {% if etape != 'pendant' %}hidden{% endif %}">
            <section>
                <div>
                    <div>
                        <a class="past">1</a>
                        <a class="current">2</a>
                        <a>3</a>
                        <a>4</a>
                        <a>5</a>
                        <a>6</a>
                        <a>7</a>
                        <a>8</a>
                        <a>9</a>
                        <a>10</a>
                        <a>11</a>
                        <a>12</a>
                    </div>
                </div>
                <div>
                    <span><span>Du</span> 01/01/2016</span>
                    <span><span>Au</span> 01/01/2016</span>
                </div>
            </section>
            <section>
                <form action="">
                    <h2>Raconte nous ta semaine</h2>
                    <span>2/12</span>
                    <textarea style="margin:30px 0;"></textarea>
                    <button class="big">Valider</button>
                </form>
            </section>
        </section>
        <section class="after formulaire current {% if etape != 'apres' %}hidden{% endif %}">
            <form action="">
                <h1>Après le stage</h1>
                <h2>Fonction(s) occupées</h2>
                <input type="text" class="big" placeholder="#Métiers">
                <h2>Compétences acquises</h2>
                <input type="text" class="big" placeholder="#Compétences">
                <h2>Commentaires personnels</h2>
                <textarea cols="30" rows="20" placeholder="Commentaires"></textarea>
                <h2>Note</h2>
                <div class="rating" style="margin-bottom:30px">
                    <span>☆</span><span>☆</span><span>☆</span><span class="note">☆</span><span>☆</span>
                </div>
                <h2>Rapport de stage</h2>
                <input type="file">
                <span style="font-size:0.8em;display:block;margin-bottom: 30px">Les fichiers doivent être au format pdf et peser moins de 20 Mo</span>
                <button class="big">Valider</button>
            </form>
        </section>
    </main>
{% endblock %}

{% block includeBody %}

    <script type="text/javascript" src="{{ asset("assets/jquery-custom.min.js") }}"></script>
    <script src="{{ asset("assets/jquery-ui-1.11.4/jquery-ui.min.js") }}"></script>

    <!--<script type="text/javascript" src="{{ asset("assets/datePicker.js") }}"></script>-->
    <script type="text/javascript" src="{{ asset("js/ajax/ajaxGetByType.js") }}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            ajaxListGetByType('Company', $('input#beforeInternship_companyId'));
        })
    </script>
    <!--
    <script>
        $('#before').click(function () {
            $('section.during, section.after').addClass("hidden");
            $('section.before').removeClass("hidden");
            $('header').removeClass();
            $('header').addClass("before");
        });


        $('#during').click(function () {
            $('section.before, section.after').addClass("hidden");
            $('section.during').removeClass("hidden");
            $('header').removeClass();
            $('header').addClass("during");
        });


        $('#after').click(function () {
            $('section.during, section.before').addClass("hidden");
            $('section.after').removeClass("hidden");
            $('header').removeClass();
            $('header').addClass("after");
        });
    </script>
    -->

{% endblock %}

src/MMIBundle/Resources/views/Stage/stages_etablis.html.twig
{% extends "MMIBundle::template.html.twig" %}

{% block title %}Attribuer tuteurs aux stages établis{% endblock %}

{% block bodyClass %}stage{% endblock %}

{% block headerExtended %}
    <div>
        <h1>Listes des stages établis</h1>

        <p>Bonjour M. Senente ! Voici la liste des stages dont la convention a été établie par Élodie.
            Elle vous permettra de définir le tuteur, la date de visite et la date de soutenance.</p>
    </div>
{% endblock %}

{% block content %}
<main class="etablis">
    <section>
        <table>
            <tr class="main">
                <td colspan="2"><p>Étudiant</p></td>
                <td><p>Fiche de stage</p></td>
                <!--<td><p>N° offre</p></td>-->
                <td><p>Entreprise</p></td>
                <td><p>Tuteur de stage</p></td>
                <td><p>Date de visite</p></td>
                <td><p>Date de soutenance</p></td>
                <td><p>Validation</p></td>
            </tr>
            {% for internship in internships %}
                {% set form = stageEtablisForms[internship.id].createView %}
                <tr>
                    <td><a href="{{ path('mmi_student', {'id': internship.userId}) }}"><span
                                    style="background-image: url({{ asset('images/profil_picture/') }}{{ internship.getUser.imageProfilFile }})">Photo de profil</span></a></td>
                    <td><a href="{{ path('mmi_student', {'id': internship.userId}) }}">{{ internship.getUser.firstName }} {{ internship.getUser.lastName }}</a></td>
                    <td><a href="{{ path('mmi_internship', {'id': internship.id}) }}" target="_blank">Accès fiche</a></td>
                    <!--<td>{% if internship.offerId != 0 %}<a href="#{{ internship.offerId }}">Offre</a>{% endif %}</td>-->
                    <td><a href="{{ path('mmi_company', {'id': internship.companyId}) }}">{{ internship.getCompany.name }}</a></td>

                    {{ form_start(form) }}

                    {{ form_widget(form.id) }}

                    <td>{{ form_widget(form.tutor_id, {'attr': {'class': 'big', 'placeholder': 'Tuteur de stage'}}) }}</td>
                    <td>{{ form_widget(form.date_visite, {'attr': {'class': 'big', 'placeholder': 'Date de visite'}}) }}</td>
                    <td>{{ form_widget(form.date_soutenance, {'attr': {'class': 'big', 'placeholder': 'Date de soutenance'}}) }}</td>
                    <td>{{ form_widget(form.valider, {'attr': {'class': 'big', 'style': 'margin-top: 30px;display: block', 'value': 'Valider'}} ) }}</td>

                    {{ form_end(form) }}

                    </td>
                </tr>
            {% endfor %}
        </table>
    </section>

    <!--
    <section class="map">
        <h1>Carte</h1>

        <p>Filtrer par tuteur :
            <select name="select" class="custom-select sources selector_type" placeholder="Tous">
                <option value="value1">Xavier Senente</option>
                <option value="value2">Xavier Senente</option>
                <option value="value3">Xavier Senente</option>
                <option value="value4">Xavier Senente</option>
            </select></p>
        <div id="map"></div>
    </section>
    -->
</main>
{% endblock %}

{% block includeBody %}

    <script src="{{ asset("assets/jquery-ui-1.11.4/jquery-ui.min.js") }}"></script>

    <script src="{{ asset('js/map_stage.js') }}"></script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpJzOJLQuJUianW27QLEzMo9Y-YWp7aW4&callback=initMap">
    </script>
    <script src="{{ asset('assets/datePicker.js') }}"></script>
    <script src="{{ asset('js/custom_select.js') }}"></script>

    <script src="{{ asset('js/ajax/ajaxGetByType.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            // Tuteur
            ajaxGetByType('Tuteur', $('input#'));

        });
    </script>
{% endblock %}

src/MMIBundle/Resources/views/Stage/stages_promo.html.twig
{% extends "MMIBundle::template.html.twig" %}

{% block title %}Stage à valider{% endblock %}

{% block bodyClass %}stage{% endblock %}

{% block headerExtended %}
    <div>
        <h1>Listes des stages de la promo</h1>

        <p>Bonjour Mme Gil ! Voici la liste des étudiants qui ont trouvé leur stage.
            Nous vous invitons à les valider.</p>
    </div>
{% endblock %}

{% block content %}
<main>
    <section>
        <table>
            <tr class="main">
                <td colspan="2"><p>Étudiant</p></td>
                <td><p>Fiche de stage</p></td>
                <!--<td><p>N° offre</p></td>-->
                <td><p>Entreprise</p></td>
                <td><p>Valider</p></td>
                <td><p>Refuser</p></td>
            </tr>

            {% for internship in internships %}
            <tr>
                <td><a href="{{ path('mmi_student', {'id': internship.userId}) }}"><span
                        style="background-image: url({{ asset('images/profil_picture/') }}{{ internship.getUser.imageProfilFile }})">Photo de profil</span></a></td>
                <td><a href="{{ path('mmi_student', {'id': internship.userId}) }}">{{ internship.getUser.firstName }} {{ internship.getUser.lastName }}</a></td>
                <td><a href="{{ path('mmi_internship', {'id': internship.id}) }}" target="_blank">Accès à la fiche</a></td>
                <!--<td>{% if internship.offerId != 0 %}<a href="#{{ internship.offerId }}">Offre</a>{% endif %}</td>-->
                <td><a href="{{ path('mmi_company', {'id': internship.companyId}) }}">{{ internship.getCompany.name }}</a></td>
                <td><a href="{{ path('mmi_internship_validation', {'id': internship.id, 'valide': '1'}) }}"><i class="fa fa-check"></i></a></td>
                <td><a href="{{ path('mmi_internship_validation', {'id': internship.id, 'valide': '2'}) }}"><i class="fa fa-times"></i></a></td>
            </tr>
            {% endfor %}
        </table>
    </section>
</main>
{% endblock %}

src/MMIBundle/Resources/views/Stage/stages_valides.html.twig
{% extends "MMIBundle::template.html.twig" %}

{% block title %}Conventions à faire{% endblock %}

{% block bodyClass %}stage{% endblock %}

{% block headerExtended %}
    <div>
        <h1>Listes des stages validés</h1>

        <p>Bonjour Elodie ! :) Voici la liste des stages validés par Mme Gil.
        Cette page vous permettra d'établir les conventions.</p>
    </div>
{% endblock %}

{% block content %}
<main>
    <section>
        <table>
            <tr class="main">
                <td colspan="2"><p>Étudiant</p></td>
                <td><p>Fiche de stage</p></td>
                <!--<td><p>N° offre</p></td>-->
                <td><p>Entreprise</p></td>
                <td><p>Générer la convention</p></td>
                <td><p>Valider la convention</p></td>
            </tr>

            {% for internship in internships %}
                <tr>
                    <td><a href="{{ path('mmi_student', {'id': internship.userId}) }}"><span
                                    style="background-image: url({{ asset('images/profil_picture/') }}{{ internship.getUser.imageProfilFile }})">Photo de profil</span></a></td>
                    <td><a href="{{ path('mmi_student', {'id': internship.userId}) }}">{{ internship.getUser.firstName }} {{ internship.getUser.lastName }}</a></td>
                    <td><a href="{{ path('mmi_internship', {'id': internship.id}) }}" target="_blank">Accès à la fiche</a></td>
                    <!--<td>{% if internship.offerId != 0 %}<a href="#{{ internship.offerId }}">Offre</a>{% endif %}</td>-->
                    <td><a href="{{ path('mmi_company', {'id': internship.companyId}) }}">{{ internship.getCompany.name }}</a></td>
                    <td><a href="{{ path('mmi_agreement_generation', {'id': internship.id}) }}"><i class="fa fa-check"></i></a></td>
                    <td><a href="{{ path('mmi_agreement_validation', {'id': internship.id}) }}"><i class="fa fa-check"></i></a></td>
                </tr>
            {% endfor %}

        </table>
    </section>
</main>
{% endblock %}